### ISSUE TITLE
Add feature to ping domain address

### ISSUE THREAD

**Issue by Vedsaga** [Vedsaga/check_network#5]
Add feature to ping specific domain address to verify if server is down-running as soon as `Internet status is Available`

### Implementation plan

- [ ] take URI as argument
- [ ] initiate http request to that URI
- [ ] check if status is 200 or not
- [ ] return a `Future<bool>`

**Comment by msarkrish** [comment]
@Vedsaga Can you assign this issue to me?

**Comment by Vedsaga** [comment]
@msarkrish done please feel free to fork it and raise the PR.

**Comment by msarkrish** [comment]
Thank you @Vedsaga
